 [workspace]
 members = [
     "contracts/kira_teminat",
 ]
 resolver = "2"
 
 [workspace.package]
 edition = "2021"
 license = "Apache-2.0"
 
 [workspace.dependencies]
 soroban-sdk = "22.0.0"
 soroban-token-sdk = "22.0.0"

